@startuml

title __PANDORA-SJAR's Class Diagram__\n

  package  {
    package controllers {
      class AccountController {
      }
    }
  }
  

  package  {
    package controllers {
      class AddGameController {
      }
    }
  }
  

  package  {
    package controllers {
      class AppController {
      }
    }
  }
  

  package  {
    package demo {
      class AttachmentInfo {
      }
    }
  }
  

  package  {
    package demo {
      class AttachmentServlet {
      }
    }
  }
  

  package  {
    class CRLFOutputStream {
    }
  }
  

  package  {
    class ComponentFrame {
    }
  }
  

  package  {
    package model {
      class DBConnection {
      }
    }
  }
  

  package  {
    class FileErrorManager {
    }
  }
  

  package  {
    package demo {
      class FilterServlet {
      }
    }
  }
  

  package  {
    class FolderModel {
    }
  }
  

  package  {
    class FolderTreeNode {
    }
  }
  

  package  {
    class FolderViewer {
    }
  }
  

  package  {
    package model {
      class Game {
      }
    }
  }
  

  package  {
    package controllers {
      class GameController {
      }
    }
  }
  

  package  {
    class JavaMailServlet {
    }
  }
  

  package  {
    package demo {
      class ListAttachmentsTEI {
      }
    }
  }
  

  package  {
    package demo {
      class ListAttachmentsTag {
      }
    }
  }
  

  package  {
    package demo {
      class ListMessagesTEI {
      }
    }
  }
  

  package  {
    package demo {
      class ListMessagesTag {
      }
    }
  }
  

  package  {
    package controllers {
      class LoginController {
      }
    }
  }
  

  package  {
    class MSBodyPart {
    }
  }
  

  package  {
    class MSMessage {
    }
  }
  

  package  {
    class MSMultipartDataSource {
    }
  }
  

  package  {
    class MailHandlerDemo {
    }
  }
  

  package  {
    package demo {
      class MailUserBean {
      }
    }
  }
  

  package  {
    class MailUserData {
    }
  }
  

  package  {
    package controllers {
      class Main {
      }
    }
  }
  

  package  {
    package demo {
      class MessageInfo {
      }
    }
  }
  

  package  {
    package demo {
      class MessageTEI {
      }
    }
  }
  

  package  {
    package demo {
      class MessageTag {
      }
    }
  }
  

  package  {
    class MessageViewer {
    }
  }
  

  package  {
    class MultipartViewer {
    }
  }
  

  package  {
    class NewlineOutputStream {
    }
  }
  

  package  {
    package controllers {
      class RegisterController {
      }
    }
  }
  

  package  {
    package demo {
      class SendTag {
      }
    }
  }
  

  package  {
    class SimpleAuthenticator {
    }
  }
  

  package  {
    class SimpleClient {
    }
  }
  

  package  {
    class StoreTreeNode {
    }
  }
  

  package  {
    class SummaryFormatter {
    }
  }
  

  package  {
    class SummaryNameFormatter {
    }
  }
  

  package  {
    class TextViewer {
    }
  }
  

  package  {
    class TreePress {
    }
  }
  

  package  {
    package model {
      class User {
      }
    }
  }
  

  package  {
    class copier {
    }
  }
  

  package  {
    class folderlist {
    }
  }
  

  package  {
    class monitor {
    }
  }
  

  package  {
    class mover {
    }
  }
  

  package  {
    class msgmultisendsample {
    }
  }
  

  package  {
    class msgsend {
    }
  }
  

  package  {
    class msgsendsample {
    }
  }
  

  package  {
    class msgshow {
    }
  }
  

  package  {
    class namespace {
    }
  }
  

  package  {
    class populate {
    }
  }
  

  package  {
    class registry {
    }
  }
  

  package  {
    class search {
    }
  }
  

  package  {
    class sendfile {
    }
  }
  

  package  {
    class sendhtml {
    }
  }
  

  package  {
    class smtpsend {
    }
  }
  

  package  {
    class transport {
    }
  }
  

  package  {
    class uidmsgshow {
    }
  }
  

  AccountController o-- User : user
  AccountController o-- User : oldUser
  AccountController o-- AppController : app
  AddGameController o-- AppController : app
  AppController o-- User : actualUser
  GameController o-- Game : game
  JavaMailServlet -up-|> SingleThreadModel
  LoginController o-- User : actualUser
  MSMultipartDataSource -up-|> MultipartDataSource
  Main -up-|> Application
  MessageViewer -up-|> CommandObject
  MultipartViewer -up-|> CommandObject
  TextViewer -up-|> CommandObject
  TreePress -up-|> TreeSelectionListener
  transport -up-|> ConnectionListener
  transport -up-|> TransportListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
