@startuml

title __CLIENT's Class Diagram__\n

  package  {
    class ComponentFrame {
        + ComponentFrame()
        + ComponentFrame()
    }
  }
  

  package  {
    class FolderModel {
        ~ folder : Folder
        ~ messages : Message[]
        ~ columnNames : String[]
        ~ columnTypes : Class[]
        {static} # cached : String[][]
        + setFolder()
        + getMessage()
        + getColumnName()
        + getColumnClass()
        + getColumnCount()
        + getRowCount()
        + getValueAt()
        # getCachedData()
    }
  }
  

  package  {
    class FolderTreeNode {
        # folder : Folder
        # hasLoaded : boolean
        + FolderTreeNode()
        + isLeaf()
        + getFolder()
        + getChildCount()
        # loadChildren()
        + toString()
    }
  }
  

  package  {
    class FolderViewer {
        ~ model : FolderModel
        ~ scrollpane : JScrollPane
        ~ table : JTable
        + FolderViewer()
        + FolderViewer()
        + setFolder()
    }
  }
  

  package  {
    class FolderPressed {
        + valueChanged()
    }
  }
  

  package  {
    class MessageViewer {
        ~ displayed : Message
        ~ dataHandler : DataHandler
        ~ verb : String
        ~ mainbody : Component
        ~ headers : TextArea
        + MessageViewer()
        + MessageViewer()
        + setMessage()
        # addToolbar()
        # loadHeaders()
        # getBodyComponent()
        + setCommandContext()
    }
  }
  

  package  {
    class StructureAction {
        ~ sb : StringBuffer
        + actionPerformed()
        # dumpPart()
    }
  }
  

  package  {
    class MultipartViewer {
        # dh : DataHandler
        # verb : String
        + MultipartViewer()
        + setCommandContext()
        # setupDisplay()
        # getComponent()
        # setupErrorDisplay()
    }
  }
  

  package  {
    class AttachmentViewer {
        ~ bp : BodyPart
        + AttachmentViewer()
        + actionPerformed()
    }
  }
  

  package  {
    class SimpleAuthenticator {
        ~ frame : Frame
        ~ username : String
        ~ password : String
        + SimpleAuthenticator()
        # getPasswordAuthentication()
        - constrain()
    }
  }
  

  package  {
    class SimpleClient {
        {static} ~ url : Vector
        {static} ~ fv : FolderViewer
        {static} ~ mv : MessageViewer
        {static} + main()
    }
  }
  

  package  {
    class StoreTreeNode {
        # store : Store
        # folder : Folder
        # display : String
        + StoreTreeNode()
        + isLeaf()
        + getChildCount()
        # loadChildren()
        + toString()
    }
  }
  

  package  {
    class TextViewer {
        - text_area : JTextArea
        - dh : DataHandler
        - verb : String
        + TextViewer()
        + setCommandContext()
        + setInputStream()
    }
  }
  

  package  {
    class TreePress {
        + valueChanged()
    }
  }
  

  FolderViewer +-down- FolderPressed
  FolderPressed -up-|> ListSelectionListener
  MessageViewer -up-|> CommandObject
  MessageViewer +-down- StructureAction
  StructureAction -up-|> ActionListener
  MultipartViewer -up-|> CommandObject
  MultipartViewer +-down- AttachmentViewer
  AttachmentViewer -up-|> ActionListener
  TextViewer -up-|> CommandObject
  TreePress -up-|> TreeSelectionListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
