@startuml

title __DEMO's Class Diagram__\n

  package  {
    package demo {
      class AttachmentInfo {
          - part : Part
          - num : int
          + getAttachmentType()
          + getContent()
          + getDescription()
          + getFilename()
          + getNum()
          + hasDescription()
          + hasFilename()
          + hasMimeType()
          + isInline()
          + setPart()
      }
    }
  }
  

  package  {
    package demo {
      class ListAttachmentsTEI {
          + ListAttachmentsTEI()
          + getVariableInfo()
      }
    }
  }
  

  package  {
    package demo {
      class ListAttachmentsTag {
          - messageinfo : String
          - partNum : int
          - numParts : int
          - attachmentinfo : AttachmentInfo
          - messageInfo : MessageInfo
          - multipart : Multipart
          + getMessageinfo()
          + setMessageinfo()
          + doStartTag()
          + doAfterBody()
          - getPart()
      }
    }
  }
  

  package  {
    package demo {
      class ListMessagesTEI {
          + ListMessagesTEI()
          + getVariableInfo()
      }
    }
  }
  

  package  {
    package demo {
      class ListMessagesTag {
          - folder : String
          - session : String
          - msgNum : int
          - messageCount : int
          - message : Message
          - messages : Message[]
          - messageinfo : MessageInfo
          + getFolder()
          + getSession()
          + setFolder()
          + setSession()
          + doStartTag()
          + doAfterBody()
          - getMessage()
      }
    }
  }
  

  package  {
    package demo {
      class MessageInfo {
          - message : Message
          + getBcc()
          + getBody()
          + getCc()
          + getDate()
          + getFrom()
          + getReplyTo()
          + getMessage()
          + getNum()
          + getReceivedDate()
          + getSentDate()
          + getSubject()
          + getTo()
          + hasAttachments()
          + hasBcc()
          + hasCc()
          + hasDate()
          + hasFrom()
          + hasMimeType()
          + hasReceivedDate()
          + hasSentDate()
          + hasSubject()
          + hasTo()
          + setMessage()
          - formatAddresses()
          - getDisplayAddress()
      }
    }
  }
  

  package  {
    package demo {
      class MessageTEI {
          + MessageTEI()
          + getVariableInfo()
      }
    }
  }
  

  package  {
    package demo {
      class MessageTag {
          - folder : String
          - session : String
          - num : int
          + getFolder()
          + getNum()
          + getSession()
          + setFolder()
          + setNum()
          + setSession()
          + doStartTag()
      }
    }
  }
  

  package  {
    package demo {
      class SendTag {
          - body : String
          - cc : String
          - host : String
          - recipients : String
          - sender : String
          - subject : String
          + setHost()
          + setRecipients()
          + setSender()
          + setCc()
          + setSubject()
          + doEndTag()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
